all:semcreate semrmid semsetvalue semgetvalue semopin semopde

semcreate:semcreate.cpp
	g++ -o semcreate semcreate.cpp

semrmid:semrmid.cpp
	g++ -o semrmid semrmid.cpp

semsetvalue:semsetvalue.cpp
	g++ -o semsetvalue semsetvalue.cpp

semgetvalue:semgetvalue.cpp
	g++ -o semgetvalue semgetvalue.cpp

semopin:semopin.cpp
	g++ -o semopin semopin.cpp

semopde:semopde.cpp
	g++ -o semopde semopde.cpp

.PHONY:clean

clean:
	rm semcreate semrmid semsetvalue semgetvalue semopin semopde
